"""empty message

Revision ID: 19fe0f9ea573
Revises: 
Create Date: 2022-12-01 08:54:52.677912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fe0f9ea573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_img', sa.String(length=255), nullable=True),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('brief_you', sa.String(length=100), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('here_for', sa.Text(), nullable=True),
    sa.Column('general', sa.Text(), nullable=True),
    sa.Column('music', sa.Text(), nullable=True),
    sa.Column('movies', sa.Text(), nullable=True),
    sa.Column('television', sa.Text(), nullable=True),
    sa.Column('books', sa.Text(), nullable=True),
    sa.Column('heroes', sa.Text(), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('snapchat', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=100), nullable=True),
    sa.Column('twitter', sa.String(length=100), nullable=True),
    sa.Column('youtube', sa.String(length=100), nullable=True),
    sa.Column('twitch', sa.String(length=100), nullable=True),
    sa.Column('tiktok', sa.String(length=100), nullable=True),
    sa.Column('soundcloud', sa.String(length=100), nullable=True),
    sa.Column('spotify', sa.String(length=100), nullable=True),
    sa.Column('pintrest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('blog_title', sa.String(length=100), nullable=False),
    sa.Column('blog_body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commenter', sa.Integer(), nullable=True),
    sa.Column('commented', sa.Integer(), nullable=True),
    sa.Column('comment_body', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['commented'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commenter'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('blogs')
    op.drop_table('users')
    # ### end Alembic commands ###